// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sigmob_config_request.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(WindGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define WindGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if WindGPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <WindFoundation/WindGPBProtocolBuffers.h>
#else
 #import "WindGPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class SigmobApp;
@class SigmobDevice;
@class SigmobNetwork;
@class SigmobPrivacy;
@class SigmobUser;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SigmobConfigRequestRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (WindGPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c WindGPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
WindGPB_FINAL @interface SigmobConfigRequestRoot : WindGPBRootObject
@end

#pragma mark - SigmobConfigRequest

typedef WindGPB_ENUM(SigmobConfigRequest_FieldNumber) {
  SigmobConfigRequest_FieldNumber_App = 1,
  SigmobConfigRequest_FieldNumber_Device = 2,
  SigmobConfigRequest_FieldNumber_Network = 3,
  SigmobConfigRequest_FieldNumber_Privacy = 4,
  SigmobConfigRequest_FieldNumber_User = 5,
};

WindGPB_FINAL @interface SigmobConfigRequest : WindGPBMessage

/** 必填！应用信息 */
@property(nonatomic, readwrite, strong, null_resettable) SigmobApp *app;
/** Test to see if @c app has been set. */
@property(nonatomic, readwrite) BOOL hasApp;

/** 必填！设备信息 */
@property(nonatomic, readwrite, strong, null_resettable) SigmobDevice *device;
/** Test to see if @c device has been set. */
@property(nonatomic, readwrite) BOOL hasDevice;

/** 必填！网络环境信息 */
@property(nonatomic, readwrite, strong, null_resettable) SigmobNetwork *network;
/** Test to see if @c network has been set. */
@property(nonatomic, readwrite) BOOL hasNetwork;

/** 用户隐私 */
@property(nonatomic, readwrite, strong, null_resettable) SigmobPrivacy *privacy;
/** Test to see if @c privacy has been set. */
@property(nonatomic, readwrite) BOOL hasPrivacy;

/** 用户信息 */
@property(nonatomic, readwrite, strong, null_resettable) SigmobUser *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
